services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: CrossEMAStochRSI1-live
    restart: unless-stopped
    volumes:
      - ../../../:/freqtrade/user_data
    command: >
      trade
      --config /freqtrade/user_data/bots/live/CrossEMAStochRSI1/config/CrossEMAStochRSI1.live.json
      --config /freqtrade/user_data/bots/live/CrossEMAStochRSI1/config/CrossEMAStochRSI1.live.private.json
      --strategy CrossEMAStochRSI1
      --strategy-path /freqtrade/user_data/strategies/approved/CrossEMAStochRSI1
      --logfile /freqtrade/user_data/bots/live/CrossEMAStochRSI1/logs/CrossEMAStochRSI1.live.log
